### ISSUE TITLE
Type of arguments

### ISSUE THREAD

**Issue by michaelimstepf** [ConsenSys/abi-decoder#1]
Awesome plugin, thanks so much.

I ran `decodeMethod` and noticed that it doesn't return the type of each argument that's passed into the function (e.g. `uint` or `address`), is there any way to get this data?

**Comment by denisgranha** [comment]
thanks for using it @michaelimstepf , I can add that parameter in a next update sure

**Comment by michaelimstepf** [comment]
@denisgranha That would be terrific, thanks so much.

I was doing research on Stackoverflow and there are lots of people new to Ethereum like myself who struggle to decode data particularly for the `input` field on transactions. Your solution solves this problem.

http://ethereum.stackexchange.com/questions/13070/decode-input-data-on-transaction
http://ethereum.stackexchange.com/questions/11144/how-to-decode-input-data-from-a-transaction
http://ethereum.stackexchange.com/questions/3364/encoding-decoding-contract-abi-data
http://ethereum.stackexchange.com/questions/6101/event-tracking-and-decoding-from-ethereumj/6331

**Comment by denisgranha** [comment]
added in e1f6ee344dbaab5d7e3c4df7baed9542f7414ea6
cool, this is the decoder we use for the [MultisigWallet](https://wallet.gnosis.pm/)
