### ISSUE TITLE
Wrong Decoding of Transaction Receipt Logs

### ISSUE THREAD

**Issue by RashikaAggarwal** [ConsenSys/abi-decoder#44]
Hi,
I am using abiDecoder.decodeLogs(receipt.logs) to decode the logs of my quorum transactions. It decodes the addresses incorrectly in the logs. 
For example- My actual account address is - 0x955**B**26**E**07213e7724**C**936b2e6765**A**b0**B**C15bdb17
but the decoded the output address comes - 0x955**b**26**e**07213e7724**c**936b2e6765**a**b0**b**c15bdb17 

Similary, another account address is - 0x1932c48b2b**f**8102**b**a33**b**4**a**6**b**545**c**32236e342f34
but the decoded output address comes - 0x1932c48b2b**F**8102**B**a33**B**4**A**6**B**545**C**32236e342f34

I am using abi-decoder version - 2.2.1 with web3 version -  1.2.1. 
Please explain the reason behind this irregular behaviour. This wrong decoding occurs in just addresses but rest of the decoded logs output comes correct.

**Comment by efiShtain** [comment]
Ethereum addresses are case insensitive, this are the same addresses

**Comment by RashikaAggarwal** [comment]
I agree these are the same addresses but earlier when i was using older versions of web3 and abi-decoder, this scenario never happened. Therefore, i wanted to know is there any reason behind this slight change in characters?

**Comment by denisgranha** [comment]
in the v2 versions of the decoder web3 v1 was added, and it uses checksum addresses
