### ISSUE TITLE
Can't decode if the function has parameters of array of int

### ISSUE THREAD

**Issue by descampsk** [ConsenSys/abi-decoder#6]
Hello,

Thanks for your job ! 

But i got an issue when i try to decode input of this function : 

{ "constant": false, "inputs": [ { "name": "personalPublicKey", "type": "uint256[2]" }, { "name": "inscriptionCode", "type": "bytes32" } ], "name": "askForRegistration", "outputs": [ { "name": "_successful", "type": "bool" }, { "name": "_error", "type": "string" } ], "payable": false, "type": "function" }

This function got a parameter which is an array of int : uint256[2].

When i'm trying to decode the input : 
"0x03f81e4bc2d9fba5a3c7528b79a64b5b3ece4fef1c8b9403177fb49050ebd203089df7cb9b5211ed7a2687c8f65821033ea8a52aa5fb5bf2e75e2d28789bf6c59310e332777a33615a67506d77494757476b4e7200000000000000000000000000000000"

I receive the following error : 

Uncaught Error: new BigNumber() not a number: 8.8133835242182733293431835969184996744628576634809496506230003714962103334859e+76,7.025349672177732334213228675287293923580409794353518492209036660848106726277e+76
    at raise (C:\Developpement\WaveVote\electron-ihm-votant\node_modules\abi-decoder\node_modules\bignumber.js\bignumber.js:1177:25)
[...]
    at params.decoded.map (C:\Developpement\WaveVote\electron-ihm-votant\node_modules\abi-decoder\index.js:76:36)

I think the decoder can't decode array of int. 

I'm trying to modify the code of your librairy to solve this issue but atm it's not a success.

If you have a solution to propose, you're welcome ! 

Best regards.

**Comment by denisgranha** [comment]
hello @descampsk ! that's an interesting issue how did you generated the ABI? uint256[2] is correct?
The decode function uses web3 decoder https://github.com/ethereum/web3.js/blob/develop/lib/solidity/coder.js

**Comment by descampsk** [comment]
Hello, 

To generate the ABI, i use the Ethereum Wallet. I use the 0.9.0 version.

I think unint256[2] is correct because i use this in solidity to pass array as function argument.

To work around this issue, i modify one function of the files index.js of your library : 

if (abiItem.inputs[index].type.valueOf() == "uint256") {
			parsedParam = new Web3().toBigNumber(param).toString(10);
		}	
        else if (abiItem.inputs[index].type.indexOf("uint") !== -1) {
			var paramLength = param.length;
			var paramHeight = param[0].length;
			
			parsedParam=new Array();
			if (paramHeight==undefined) {
				for(var i=0;i<param.length;i++) {
					parsedParam.push(new Web3().toBigNumber(param[i]).toString(10));
				}
			} else {
				for(var i=0;i<param.length;i++) {
					var paramArray = param[i];
					var secondArray = new Array();
					for(var j=0;j<paramArray.length;j++) {
						secondArray.push(new Web3().toBigNumber(param[i][j]).toString(10));
					}
					parsedParam.push(secondArray);
				}
			}
        }

It works for 1D array and 2D array, but i dont know if it is the best solution.

What do you think ?

**Comment by kabl** [comment]
Hello there

Thanks for this library. It's very simple to use. 

I have the same issue with an array of uint256. The library throws an error by trying to decode it. 

Function signature: 
`function mint(address[] recipients, uint256[] tokens) public  returns (bool)`

ABI: 
`
{
        "constant": false,
        "inputs": [
            {
                "name": "recipients",
                "type": "address[]"
            },
            {
                "name": "tokens",
                "type": "uint256[]"
            }
        ],
        "name": "mint",
        "outputs": [
            {
                "name": "",
                "type": "bool"
            }
        ],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
    },
`

When i call this method with following parameter: 
`["0xab...12", "0x5a...32"], [100000000000, 100000000000]`

Exception: 
`
message: "new BigNumber() not a number: 100000000000,100000000000"
name: "BigNumber Error"
stack: "BigNumber Error: new BigNumber() not a number: 100000000000,100000000000
    at raise (/PATH/node_modules/bignumber.js/bignumber.js:1177:25)
    at /PATH/node_modules/bignumber.js/bignumber.js:1165:33
    at new BigNumber (/PATH/node_modules/bignumber.js/bignumber.js:193:67)
    at new BigNumber (/PATH/node_modules/bignumber.js/bignumber.js:203:25)
    at Web3.toBigNumber (/PATH/node_modules/abi-decoder/node_modules/web3/lib/utils/utils.js:367:12)
    at params.decoded.map (/PATH/node_modules/abi-decoder/index.js:76:36)
    at Array.map (<anonymous>)
    at Object._decodeMethod [as decodeMethod] (/PATH/node_modules/abi-decoder/index.js:73:23)
    at MethodNameInsp.inspect (/PATH/dist/Inspectors.js:50:33)
    at inspectors.forEach.inspt (/PATH/dist/ContractObserve.js:48:62)"
`
